# Generated by Django 5.2.7 on 2025-10-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='perusahaan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
