# Generated by Django 5.2.7 on 2025-10-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mahasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='magang',
            field=models.BooleanField(default=False),
        ),
    ]
