# Generated by Django 5.2.7 on 2025-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_mahasiswa_email_alter_mahasiswa_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='cv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='porto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
