# Generated by Django 5.2.7 on 2025-12-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mahasiswa_cv_mahasiswa_porto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(
                blank=True,
                choices=[
                    ('BBA', 'Bachelor of Business Administration'),
                    ('BSBA', 'Bachelor of Science in Business Analytics'),
                    ('BSSE', 'Bachelor of Science in Software Engineering'),
                    ('BIE', 'Bachelor of Industrial Engineering')
                ],
                max_length=10,
                null=True,
                verbose_name='Jurusan'
            ),
        ),
        migrations.CreateModel(
            name='Kaprodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('jurusan', models.CharField(
                    choices=[
                        ('BBA', 'Bachelor of Business Administration'),
                        ('BSBA', 'Bachelor of Science in Business Analytics'),
                        ('BSSE', 'Bachelor of Science in Software Engineering'),
                        ('BIE', 'Bachelor of Industrial Engineering')
                    ],
                    max_length=10,
                    verbose_name='Jurusan'
                )),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nomor HP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='kaprodi_profile',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='User Account'
                )),
            ],
            options={
                'verbose_name': 'Kaprodi',
                'verbose_name_plural': 'Kaprodi',
                'ordering': ['-created_at'],
            },
        ),
    ]
