# Generated by Django 5.2.7 on 2025-10-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfirmasiMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=200)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('alamat_perusahaan', models.TextField()),
                ('bidang_usaha', models.CharField(max_length=200)),
                ('nama_supervisor', models.CharField(max_length=200)),
                ('email_supervisor', models.EmailField(max_length=254)),
                ('wa_supervisor', models.CharField(blank=True, max_length=20, null=True)),
                ('surat_penerimaan', models.FileField(upload_to='surat_magang/')),
                ('status', models.BooleanField(default=True)),
                ('mahasiswa', models.OneToOneField(limit_choices_to={'role': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
