# Generated by Django 5.2.7 on 2025-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konfirmasimagang',
            name='periode',
        ),
        migrations.AddField(
            model_name='konfirmasimagang',
            name='periode_akhir',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='konfirmasimagang',
            name='periode_awal',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
