# Generated by Django 5.2.7 on 2025-10-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0002_remove_konfirmasimagang_periode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konfirmasimagang',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
