# Generated by Django 5.2.7 on 2025-10-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0003_alter_konfirmasimagang_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfirmasimagang',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konfirmasimagang',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konfirmasimagang',
            name='requires_weekly_report',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('konfirmasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='coops.konfirmasimagang')),
            ],
        ),
    ]
