# Generated by Django 5.2.7 on 2025-10-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0004_konfirmasimagang_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluasiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('uts', 'UTS - Laporan Kemajuan'), ('uas', 'UAS - Laporan Akhir')], max_length=20)),
                ('pertanyaan', models.JSONField(help_text='Array of questions for the evaluation')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ringkasan_kegiatan', models.TextField(help_text='Ringkasan kegiatan selama magang')),
                ('pencapaian', models.TextField(help_text='Pencapaian dan hasil yang diperoleh')),
                ('kendala_solusi', models.TextField(help_text='Kendala yang dihadapi dan solusinya')),
                ('saran_perusahaan', models.TextField(help_text='Saran untuk perusahaan')),
                ('saran_kampus', models.TextField(help_text='Saran untuk kampus')),
                ('file_laporan', models.FileField(blank=True, null=True, upload_to='laporan_akhir/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konfirmasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_akhir', to='coops.konfirmasimagang')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluasiSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.JSONField(help_text='Answers corresponding to template questions')),
                ('status', models.CharField(choices=[('pending', 'Belum Diisi'), ('completed', 'Sudah Diisi')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('konfirmasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coops.konfirmasimagang')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coops.evaluasitemplate')),
            ],
            options={
                'unique_together': {('konfirmasi', 'template')},
            },
        ),
        migrations.CreateModel(
            name='LaporanKemajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('profil_perusahaan', models.TextField(help_text='Profil perusahaan')),
                ('jobdesk', models.TextField(help_text='Jobdesk yang dikerjakan')),
                ('suasana_lingkungan', models.TextField(help_text='Suasana lingkungan pekerjaan')),
                ('manfaat_perkuliahan', models.TextField(help_text='Apa yang didapatkan dari perkuliahan yang berguna untuk pekerjaan')),
                ('kebutuhan_pembelajaran', models.TextField(help_text='Apa yang berguna pada perusahaan tapi belum didapatkan dalam pembelajaran')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konfirmasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_kemajuan', to='coops.konfirmasimagang')),
            ],
            options={
                'unique_together': {('konfirmasi', 'bulan')},
            },
        ),
    ]
