# Generated by Django 5.2.7 on 2025-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0005_evaluasitemplate_laporanakhir_evaluasisupervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluasisupervisor',
            name='jawaban',
            field=models.JSONField(blank=True, default=dict, help_text='Answers corresponding to template questions'),
        ),
    ]
