# Generated by Django 5.2.7 on 2025-10-03 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0006_alter_evaluasisupervisor_jawaban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='konfirmasimagang',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SertifikatCoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sertifikat', models.CharField(max_length=50, unique=True)),
                ('nilai_akhir', models.CharField(choices=[('A', 'A (Sangat Baik)'), ('B', 'B (Baik)'), ('C', 'C (Cukup)'), ('D', 'D (Kurang)')], help_text='Konversi nilai untuk mata kuliah Coop', max_length=2)),
                ('tanggal_kelulusan', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Diterbitkan'), ('revoked', 'Dicabut')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dikeluarkan_oleh', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('konfirmasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat', to='coops.konfirmasimagang')),
            ],
        ),
    ]
