# Generated by Django 5.2.7 on 2025-10-03 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0008_auto_20251003_1149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklyreport',
            name='coops_weeklyreport_student_week_start_date_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('student', 'week_start_date')},
        ),
    ]
